version: "3.8"
services:
  postgres:
    image: postgres:14.10-alpine3.19
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "crack"
      POSTGRES_USER: "crack_user"
      POSTGRES_PASSWORD: "crack_pass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./rearguarde/configuration/init_scripts:/docker-entrypoint-initdb.d
      - local_crack_storage:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crack_user -d crack"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: on-failure:2
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
volumes:
  local_crack_storage:
